version: 0.0.1
achievements:
  - achievement:
      name: Every Bit Counts
      icon: https://raw.githubusercontent.com/keploy/keploy/main/.vaunt/badge/commit_hero.png
      description: No commit is too small!
      triggers:
        - trigger:
            actor: author
            action: commit
            condition: count() >= 10
  - achievement:
      name: Pull Request Hero
      icon: https://raw.githubusercontent.com/keploy/keploy/main/.vaunt/badge/pull_request_hero.png
      description: You're a PR hero, rock on!
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 5
  - achievement:
      name: Docs Maker
      icon: https://raw.githubusercontent.com/keploy/keploy/main/.vaunt/badge/docs_hero.png
      description: Kudos for improving documentation!
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: closed = true & labels in ['Documentation']
  - achievement:
      name: Closer
      icon: https://raw.githubusercontent.com/keploy/keploy/main/.vaunt/badge/closer.png
      description: Only closers get coffee!!
      triggers:
        - trigger:
            actor: assignees
            action: issue
            condition: closed = true