contact_links:
  - name: Help and support
    url: https://keploy.slack.com/join/shared_invite/zt-357qqm9b5-PbZRVu3Yt2rJIa6ofrwWNg
    about: Reach out to us on our Slack channel or Discourse discussions or GitHub discussions.
  - name: Dedicated support
    url: mailto:hello@keploy.io
    about: Write to us if you'd like dedicated support using Keploy