version: api.keploy.io/v1beta2
kind: Mongo
name: config
spec:
    metadata:
        operation: '{ OpQuery flags: [SecondaryOK], fullCollectionName: admin.$cmd, numberToSkip: 0, numberToReturn: -1, query: {"isMaster": {"$numberInt":"1"},"helloOk": true,"compression": [],"client": {"driver": {"name": "mongo-go-driver","version": "v1.8.3"},"os": {"type": "linux","architecture": "amd64"},"platform": "go1.20.5"}}, returnFieldsSelector:  }'
    requests:
        - header:
            length: 230
            requestId: 2
            responseTo: 0
            Opcode: 2004
          message:
            flags: 4
            collection_name: admin.$cmd
            number_to_skip: 0
            number_to_return: -1
            query: '{"isMaster":{"$numberInt":"1"},"helloOk":true,"compression":[],"client":{"driver":{"name":"mongo-go-driver","version":"v1.8.3"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.20.5"}}'
            return_fields_selector: ""
          read_delay: 1564667
    responses:
        - header:
            length: 329
            requestId: 123
            responseTo: 2
            Opcode: 1
          message:
            response_flags: 8
            cursor_id: 0
            starting_from: 0
            number_returned: 1
            documents:
                - '{"helloOk":true,"ismaster":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxBsonObjectSize":{"$numberInt":"16777216"},"maxMessageSizeBytes":{"$numberInt":"48000000"},"maxWriteBatchSize":{"$numberInt":"100000"},"localTime":{"$date":{"$numberLong":"1689848559401"}},"logicalSessionTimeoutMinutes":{"$numberInt":"30"},"connectionId":{"$numberInt":"10"},"minWireVersion":{"$numberInt":"0"},"maxWireVersion":{"$numberInt":"17"},"readOnly":false,"ok":{"$numberDouble":"1.0"}}'
          read_delay: 2369751
    created: 1689848559
---
version: api.keploy.io/v1beta2
kind: Mongo
name: config
spec:
    metadata:
        operation: '{ OpMsg flags: 0, sections: [{ SectionSingle msg: {"hello":{"$numberInt":"1"},"helloOk":true,"$db":"admin"} }], checksum: 0 }'
    requests:
        - header:
            length: 62
            requestId: 6
            responseTo: 0
            Opcode: 2013
          message:
            flagBits: 0
            sections:
                - '{ SectionSingle msg: {"hello":{"$numberInt":"1"},"helloOk":true,"$db":"admin"} }'
            checksum: 0
          read_delay: 1799987838536
    responses:
        - header:
            length: 323
            requestId: 145
            responseTo: 6
            Opcode: 2013
          message:
            flagBits: 0
            sections:
                - '{ SectionSingle msg: {"helloOk":true,"isWritablePrimary":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxBsonObjectSize":{"$numberInt":"16777216"},"maxMessageSizeBytes":{"$numberInt":"48000000"},"maxWriteBatchSize":{"$numberInt":"100000"},"localTime":{"$date":{"$numberLong":"1689850359397"}},"logicalSessionTimeoutMinutes":{"$numberInt":"30"},"connectionId":{"$numberInt":"9"},"minWireVersion":{"$numberInt":"0"},"maxWireVersion":{"$numberInt":"17"},"readOnly":false,"ok":{"$numberDouble":"1.0"}} }'
            checksum: 0
          read_delay: 30381
    created: 1689850359
---
version: api.keploy.io/v1beta2
kind: Mongo
name: config
spec:
    metadata:
        operation: '{ OpMsg flags: 65536, sections: [{ SectionSingle msg: {"hello":{"$numberInt":"1"},"helloOk":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxAwaitTimeMS":{"$numberLong":"1800000"},"$db":"admin"} }], checksum: 0 }'
    requests:
        - header:
            length: 148
            requestId: 3
            responseTo: 0
            Opcode: 2013
          message:
            flagBits: 65536
            sections:
                - '{ SectionSingle msg: {"hello":{"$numberInt":"1"},"helloOk":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxAwaitTimeMS":{"$numberLong":"1800000"},"$db":"admin"} }'
            checksum: 0
          read_delay: 31680
    responses:
        - header:
            length: 323
            requestId: 146
            responseTo: 3
            Opcode: 2013
          message:
            flagBits: 2
            sections:
                - '{ SectionSingle msg: {"helloOk":true,"isWritablePrimary":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxBsonObjectSize":{"$numberInt":"16777216"},"maxMessageSizeBytes":{"$numberInt":"48000000"},"maxWriteBatchSize":{"$numberInt":"100000"},"localTime":{"$date":{"$numberLong":"1689850359505"}},"logicalSessionTimeoutMinutes":{"$numberInt":"30"},"connectionId":{"$numberInt":"10"},"minWireVersion":{"$numberInt":"0"},"maxWireVersion":{"$numberInt":"17"},"readOnly":false,"ok":{"$numberDouble":"1.0"}} }'
            checksum: 0
          read_delay: 1800096802845
    created: 1689850359
