name: Golang On Docker
on: [pull_request]
jobs:
  golang_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build docker image
      run: |
        docker build -t keployv2 .
    - name: Checkout the samples-go repository
      uses: actions/checkout@v2
      with:
        repository: keploy/samples-go
        path: samples-go
    - name: Run gin-mongo application
      run: |
        cd samples-go/gin-mongo
        source ./../../.github/workflows/workflow_scripts/golang-docker.sh

