name: Java on Linux
on: [pull_request]
jobs:
  java_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Keploy binary
      run: |
        go build -o keployv2

    - name: Checkout samples-java repository
      uses: actions/checkout@v2
      with:
        repository: keploy/samples-java
        path: spring-petclinic-rest

    - name: Installing the necessary dependencies
      run: |
        cd samples-java/spring-petclinic/spring-petclinic-rest
        ./mvnw dependency:resolve

    - name: Compile the project
      run: |
       cd samples-java/spring-petclinic/spring-petclinic-rest
        source ./../.github/workflows/update-java.sh
        ./mvnw compile

    - name: Run the spring-petclinic-rest app
      run: |
        cd samples-java/spring-petclinic/spring-petclinic-rest
        source ./../.github/workflows/java-linux.sh