name: Node on Docker
on: [pull_request]

jobs:
  node_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build script
      run: |
        source ./.github/workflows/test_workflow_scripts/update-docker.sh

    - name: Build binary
      run: |
        go build  -tags=viper_bind_struct -o keployv2

    - name: Checkout samples-typescript repository
      uses: actions/checkout@v2
      with:
        repository: keploy/samples-typescript
        path: samples-typescript

    - name: Run the express-mongoose app
      run: |
        cd samples-typescript/express-mongoose
        source ./../../.github/workflows/test_workflow_scripts/node-docker.sh
