name: Telemetry

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build Keploy
        run: |
          go build -v ./...

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Setup java Sample project
        run: |
          git clone https://github.com/keploy/samples-java.git &&
          curl 'https://repo1.maven.org/maven2/io/keploy/agent/1.2.6/agent-1.2.6.jar' --compressed --output samples-java/agent.jar -slient

      - name: Run Keploy and java project
        run: |
          go run ./cmd/server/main.go &
          sudo apt update &&
          sudo apt install maven -y &&
          cd samples-java &&
          export KEPLOY_MODE=test &&
          export JAVA_TOOL_OPTIONS=-javaagent:${PWD}/agent.jar &&
          count=1
          for i in $(seq $count); do
            mvn spring-boot:run
          done
          echo installation-id &&
          cat /root/keploy-config/installation-id.yaml
